name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  test-without-cuda:
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install CMAKE
      run: pip install cmake
    - name: print content of current dir
      run: python -c "import os; print('\n'.join(os.listdir('.')))"
    - name: run detection script
      run: python detection.py


  test-with-cuda:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:

    - name: install cuda toolkit
      uses: Jimver/cuda-toolkit@v0.2.23
      id: cuda-toolkit
      with:
        cuda: '12.8.1'
        use-github-cache: false
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install CMAKE
      run: pip install cmake
    - name: print content of current dir
      run: python -c "import os; print('\n'.join(os.listdir('.')))"
    - name: run detection script
      run: python detection.py