name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Test
      run: |
        pip install cmake
        ls